name: Build OpenWRT package (test)

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version to test'
        required: true
        default: 'both'
        type: choice
        options:
        # - '23.05'
        - '24.10'
        # - 'both'
      verbose:
        description: 'Verbose build output'
        required: false
        default: false
        type: boolean

jobs:
  build-test:
    name: Build Test - OpenWrt ${{ matrix.openwrt_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - openwrt_version: '23.05'
          #   arch: 'x86_64-23.05.0'
          - openwrt_version: '24.10'
            arch: 'x86_64-24.10.0'
      fail-fast: false
    
    steps:
      - name: Check if version should be built
        run: |
          # Check if this matrix combination should be built
          if [ "${{ github.event.inputs.openwrt_version }}" != "both" ] && [ "${{ github.event.inputs.openwrt_version }}" != "${{ matrix.openwrt_version }}" ]; then
            echo "Skipping build: OpenWrt version mismatch (requested: ${{ github.event.inputs.openwrt_version }}, matrix: ${{ matrix.openwrt_version }})"
            exit 0
          fi
          
          echo "Proceeding with build for OpenWrt ${{ matrix.openwrt_version }}"

      - name: Free space
        run: |
          echo "=============================================================================="
          echo "Freeing up disk space on CI system"
          echo "=============================================================================="

          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          df -h

      - name: Create feeds directory structure
        run: |
          mkdir -p ${{ github.workspace }}/feed

      # - name: Checkout repository
      #   uses: actions/checkout@v4
        # with:
        #   path: ${{ github.workspace }}/feed/luci-app-podman

      - name: Create artifacts directory structure
        run: |
          mkdir -p ${{ github.workspace }}/artifacts

      - name: Build OpenWrt ${{ matrix.openwrt_version }} package
        uses: Zerogiven/gh-action-openwrt-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: podman
          V: ${{ github.event.inputs.verbose == 'true' && 'sc' || '0' }}
          FEED_DIR: ${{ github.workspace }}/feed
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts

      # - name: Verify package built
      #   run: find ${{ github.workspace }}/artifacts/bin/ -name 'luci-app-podman*.ipk' -type f | grep . 